/*
Mark2 project 
*/

console.log("   ");

var userInput = require("readline-sync");

var userName = userInput.question("What is your Name ? ");

console.log(`Welcome ${userName}.

Lets paly a quiz to check your understanding About Goodwill. 

Alert :- There is Negative Marking. So be careful.


`);

score = 0;

function play(questions, answer) {
  var userChoose = userInput.question(questions);

  console.log("You choose :- ", userChoose);

  if (userChoose.toUpperCase() == answer) {
    console.log("right !");
    score++;
  } else {
    console.log("wrong! ");
    score--
  }

  console.log(`Your Score ${score} 
  
  `)
}

var data = [
  {
    questions: `What is goodwill?
    a) The excess of the value of a business over its tangible assets
    b) The value of tangible assets owned by a business
    c) The cost of acquiring a business
    d) The net profit generated by a business 
    
    `,

    answer: "A",
  },
  {
    questions: `Goodwill is usually recorded in the books of accounts when:
    a) It can be objectively measured
    b) The business is being sold
    c) The business incurs a loss
    d) The business is in the growth phase
    
    `,

    answer: "B",
  },
  {
    questions:`What is superprofit?
    a) The excess profit earned by a business due to its superior performance
    b) The profit earned by a business in the first year of its operation
    c) The profit earned by a business from its core operations
    d) The profit earned by a business after deducting all expenses
    
    `,

    answer:"A"
  },

  {
    questions:`Average profit is calculated by dividing:
    a) Total revenue by the number of years
    b) Total expenses by the number of years
    c) Net profit by the number of years
    d) Goodwill by the number of years`
    
    ,

    answer:"C"
  },

  {
    questions:`What is normal profit?
    a) The profit earned by a business in its initial years
    b) The profit earned by a business in a competitive market
    c) The profit earned by a business after deducting all expenses
    d) The profit earned by a business from non-core operations
    
    `,

    answer:"A"
  }

  ,{
    questions:`Normal profit can be defined as:
    a) The minimum profit required to cover all costs and provide a reasonable return on investment
    b) The maximum profit a business can earn in a specific market
    c) The profit earned by a business in a monopoly market
    d) The profit earned by a business from its core operations
    
    `,

    answer:"A"
  },

  {
    questions:`Which of the following statements is true about goodwill?
    a) Goodwill is an intangible asset and is always recorded at its market value.
    b) Goodwill represents the value of tangible assets owned by a business.
    c) Goodwill is recorded in the books of accounts only when a business is being sold.
    d) Goodwill cannot be calculated or measured objectively.
    
    `,

    answer:"D"
  }
];


for(i=0; i<data.length; i++){
    var quiz=data[i]
    play(quiz.questions,quiz.answer)

}

console.log("Your final score",score)

console.log(`Thanks For playing.

Please take a moment to provide us with your valuable feedback.
`)